   0.0 TL | Telepresence launched at Sun Jan  7 19:46:06 2018
   0.0 TL |   ['/usr/local/bin/telepresence', '--method', 'inject-tcp', '--swap-deployment', 'kubeapps-dashboard-ui', '--expose', '3000:8080', '--run', 'yarn', 'run', 'start']
   0.0 TL | Scout info: {'latest_version': '0.72', 'application': 'telepresence', 'notices': []}
   0.0 TL | Context: docker-for-desktop, namespace: kubeapps, kubectl_command: kubectl
   0.0 TL | [1] Capturing: (['kubectl', '--context', 'docker-for-desktop', 'cluster-info'],)...
   0.1 TL | [1] captured.
   0.1 TL | [2] Capturing: (['ssh', '-V'],)...
   0.1 TL | [2] captured.
   0.1 TL | [3] Capturing: (['which', 'torsocks'],)...
   0.1 TL | [3] captured.
   0.1 TL | [4] Capturing: (['which', 'sshfs'],)...
   0.1 TL | [4] captured.
   0.1 TL | [5] Capturing: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'get', 'deployment', '-o', 'json', '--export', 'kubeapps-dashboard-ui'],)...
   0.3 TL | [5] captured.
   0.3 TL | [6] Running: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'delete', 'deployment', 'kubeapps-dashboard-ui'],)...
   3.5 6 | deployment "kubeapps-dashboard-ui" deleted
   3.5 TL | [6] ran.
   3.5 TL | [7] Running: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'apply', '-f', '-'],)...
   3.8 TL | [7] ran.
   3.8 TL | [8] Capturing: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'get', 'deployment', '-o', 'json', '--export', '--selector=telepresence=562c6226-f803-4c88-865a-2c53fa591608'],)...
   4.3 TL | [8] captured.
   4.3 TL | Expected metadata for pods: {'creationTimestamp': None, 'labels': {'app': 'kubeapps-dashboard', 'created-by': 'kubeapps', 'name': 'kubeapps-dashboard-ui', 'telepresence': '562c6226-f803-4c88-865a-2c53fa591608'}}
   4.3 TL | [9] Capturing: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'get', 'pod', '-o', 'json', '--export'],)...
   4.6 TL | [9] captured.
   4.6 TL | Checking {'app': 'apprepository-controller', 'created-by': 'kubeapps', 'name': 'apprepository-controller', 'pod-template-hash': '3698788834'} (phase Running)...
   4.6 TL | Labels don't match.
   4.6 TL | Checking {'app': 'chartsvc', 'created-by': 'kubeapps', 'name': 'chartsvc', 'pod-template-hash': '2834434692'} (phase Running)...
   4.6 TL | Labels don't match.
   4.6 TL | Checking {'created-by': 'kubeapps', 'name': 'default-http-backend', 'pod-template-hash': '2095998121'} (phase Running)...
   4.6 TL | Labels don't match.
   4.6 TL | Checking {'app': 'kubeapps-dashboard', 'created-by': 'kubeapps', 'name': 'kubeapps-dashboard-api', 'pod-template-hash': '2367670574'} (phase Running)...
   4.6 TL | Labels don't match.
   4.6 TL | Checking {'app': 'kubeapps-dashboard', 'created-by': 'kubeapps', 'name': 'kubeapps-dashboard-ui', 'pod-template-hash': '1870364828'} (phase Running)...
   4.6 TL | Labels don't match.
   4.6 TL | Checking {'app': 'kubeapps-dashboard', 'created-by': 'kubeapps', 'name': 'kubeapps-dashboard-ui', 'pod-template-hash': '3816717388', 'telepresence': '562c6226-f803-4c88-865a-2c53fa591608'} (phase Pending)...
   4.6 TL | Looks like we've found our pod!
   4.6 TL | [10] Capturing: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'get', 'pod', 'kubeapps-dashboard-ui-7d5bc5c7dd-gpwm6', '-o', 'json'],)...
   4.8 TL | [10] captured.
   5.0 TL | [11] Capturing: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'get', 'pod', 'kubeapps-dashboard-ui-7d5bc5c7dd-gpwm6', '-o', 'json'],)...
   5.2 TL | [11] captured.
   5.5 TL | [12] Capturing: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'get', 'pod', 'kubeapps-dashboard-ui-7d5bc5c7dd-gpwm6', '-o', 'json'],)...
   5.7 TL | [12] captured.
   5.9 TL | [13] Capturing: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'get', 'pod', 'kubeapps-dashboard-ui-7d5bc5c7dd-gpwm6', '-o', 'json'],)...
   6.2 TL | [13] captured.
   6.5 TL | [14] Capturing: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'get', 'pod', 'kubeapps-dashboard-ui-7d5bc5c7dd-gpwm6', '-o', 'json'],)...
   6.6 TL | [14] captured.
   6.6 TL | [15] Launching: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'logs', '-f', 'kubeapps-dashboard-ui-7d5bc5c7dd-gpwm6', '--container', 'ui'],)...
   6.6 TL | [16] Launching: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'port-forward', 'kubeapps-dashboard-ui-7d5bc5c7dd-gpwm6', '55137:8022'],)...
   6.7 TL | [17] Running: (['ssh', '-F', '/dev/null', '-q', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-p', '55137', 'telepresence@localhost', '/bin/true'],)...
   6.8 TL | [17] exit 255.
   7.0 TL | [18] Running: (['ssh', '-F', '/dev/null', '-q', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-p', '55137', 'telepresence@localhost', '/bin/true'],)...
   7.0 TL | [18] exit 255.
   7.3 TL | [19] Running: (['ssh', '-F', '/dev/null', '-q', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-p', '55137', 'telepresence@localhost', '/bin/true'],)...
   7.3 16 | Forwarding from 127.0.0.1:55137 -> 8022
   7.3 16 | Handling connection for 55137
   8.1 TL | [19] ran.
   8.1 TL | [20] Launching: (['ssh', '-N', '-oServerAliveInterval=1', '-oServerAliveCountMax=10', '-F', '/dev/null', '-q', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-p', '55137', 'telepresence@localhost', '-R', '*:8080:127.0.0.1:3000'],)...
   8.1 TL | [21] Launching: (['ssh', '-N', '-oServerAliveInterval=1', '-oServerAliveCountMax=10', '-F', '/dev/null', '-q', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-p', '55137', 'telepresence@localhost', '-L', '127.0.0.1:55151:127.0.0.1:9050'],)...
   8.1 TL | [22] Capturing: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'exec', 'kubeapps-dashboard-ui-7d5bc5c7dd-gpwm6', '--container', 'ui', 'env'],)...
   8.1 16 | Handling connection for 55137
   8.1 16 | Handling connection for 55137
   9.3 TL | [22] captured.
   9.3 TL | [23] Running: (['sshfs', '-p', '55137', '-F', '/dev/null', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', 'telepresence@localhost:/', '/tmp/tmpx1v7225p'],)...
   9.4 16 | Handling connection for 55137
   9.9 TL | [23] ran.
  11.1 TL | [24] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  11.2 TL | [24] exit 1.
  11.2 24 | Traceback (most recent call last):
  11.2 24 |   File "<string>", line 1, in <module>
  11.2 24 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  11.3 TL | [25] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  11.4 TL | [25] exit 1.
  11.5 25 | Traceback (most recent call last):
  11.5 25 |   File "<string>", line 1, in <module>
  11.5 25 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  11.5 TL | [26] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  11.7 TL | [26] exit 1.
  11.7 26 | Traceback (most recent call last):
  11.7 26 |   File "<string>", line 1, in <module>
  11.7 26 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  11.8 TL | [27] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  11.9 TL | [27] exit 1.
  12.0 TL | [28] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  12.0 27 | Traceback (most recent call last):
  12.0 27 |   File "<string>", line 1, in <module>
  12.0 27 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  12.1 TL | [28] exit 1.
  12.2 TL | [29] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  12.2 28 | Traceback (most recent call last):
  12.2 28 |   File "<string>", line 1, in <module>
  12.2 28 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  12.3 TL | [29] exit 1.
  12.4 TL | [30] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  12.4 29 | Traceback (most recent call last):
  12.4 29 |   File "<string>", line 1, in <module>
  12.4 29 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  12.5 TL | [30] exit 1.
  12.6 TL | [31] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  12.6 30 | Traceback (most recent call last):
  12.6 30 |   File "<string>", line 1, in <module>
  12.6 30 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  12.8 TL | [31] exit 1.
  12.8 31 | Traceback (most recent call last):
  12.8 31 |   File "<string>", line 1, in <module>
  12.8 31 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  12.9 TL | [32] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  13.0 TL | [32] exit 1.
  13.1 32 | Traceback (most recent call last):
  13.1 32 |   File "<string>", line 1, in <module>
  13.1 32 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  13.1 TL | [33] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  13.2 TL | [33] exit 1.
  13.3 TL | [34] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  13.3 33 | Traceback (most recent call last):
  13.3 33 |   File "<string>", line 1, in <module>
  13.3 33 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  13.4 TL | [34] exit 1.
  13.5 34 | Traceback (most recent call last):
  13.5 34 |   File "<string>", line 1, in <module>
  13.5 34 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  13.5 TL | [35] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  13.6 TL | [35] exit 1.
  13.7 35 | Traceback (most recent call last):
  13.7 35 |   File "<string>", line 1, in <module>
  13.7 35 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  13.7 TL | [36] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  13.8 TL | [36] exit 1.
  13.9 36 | Traceback (most recent call last):
  13.9 36 |   File "<string>", line 1, in <module>
  13.9 36 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  13.9 TL | [37] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  14.0 TL | [37] exit 1.
  14.1 37 | Traceback (most recent call last):
  14.1 37 |   File "<string>", line 1, in <module>
  14.1 37 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  14.1 TL | [38] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  14.2 TL | [38] exit 1.
  14.3 TL | [39] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  14.3 38 | Traceback (most recent call last):
  14.3 38 |   File "<string>", line 1, in <module>
  14.3 38 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  14.5 TL | [39] exit 1.
  14.5 39 | Traceback (most recent call last):
  14.5 39 |   File "<string>", line 1, in <module>
  14.5 39 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  14.6 TL | [40] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  14.7 TL | [40] exit 1.
  14.8 40 | Traceback (most recent call last):
  14.8 40 |   File "<string>", line 1, in <module>
  14.8 40 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  14.8 TL | [41] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  14.9 TL | [41] exit 1.
  15.0 41 | Traceback (most recent call last):
  15.0 41 |   File "<string>", line 1, in <module>
  15.0 41 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  15.0 TL | [42] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  15.1 TL | [42] exit 1.
  15.1 15 | Listening...
  15.1 15 | 2018-01-07T19:46:19+0000 [-] Loading ./forwarder.py...
  15.1 15 | 2018-01-07T19:46:20+0000 [-] SOCKSv5Factory starting on 9050
  15.1 15 | 2018-01-07T19:46:20+0000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7f8169b299b0>
  15.1 15 | 2018-01-07T19:46:20+0000 [-] /etc/resolv.conf changed, reparsing
  15.1 15 | 2018-01-07T19:46:20+0000 [-] Resolver added ('10.96.0.10', 53) to server list
  15.1 15 | 2018-01-07T19:46:20+0000 [-] DNSDatagramProtocol starting on 9053
  15.1 15 | 2018-01-07T19:46:20+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f8169b3ec88>
  15.1 15 | 2018-01-07T19:46:20+0000 [-] Loaded.
  15.1 15 | 2018-01-07T19:46:20+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 17.9.0 (/usr/bin/python3.6 3.6.1) starting up.
  15.1 15 | 2018-01-07T19:46:20+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  15.2 42 | Traceback (most recent call last):
  15.2 42 |   File "<string>", line 1, in <module>
  15.2 42 | socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
  15.2 TL | [43] Running: (['torsocks', 'python3', '-c', "import socket; socket.socket().connect(('google.com', 80))"],)...
  15.4 TL | [43] ran.
52169.1 TL | Shutting down local process...
52169.2 TL | [44] Capturing: (['umount', '-f', '/tmp/tmpx1v7225p'],)...
52169.3 TL | [44] captured.
52169.4 TL | [45] Running: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'delete', 'deployment', 'kubeapps-dashboard-ui'],)...
52169.4 20 | Connection to localhost closed by remote host.
52169.4 21 | Connection to localhost closed by remote host.
52172.7 45 | deployment "kubeapps-dashboard-ui" deleted
52172.7 TL | [45] ran.
52172.7 TL | [46] Running: (['kubectl', '--context', 'docker-for-desktop', '--namespace', 'kubeapps', 'apply', '-f', '-'],)...
52173.0 46 | deployment "kubeapps-dashboard-ui" created
52173.0 TL | [46] ran.
